### ISSUE TITLE
Does not work for multiple save paths

### ISSUE THREAD

**Issue by p-hueber** [JakeWharton/qbt-orphaned-downloads#11]
Hi!

Running `qbt-orphaned-downloads`, all my files and torrents are marked unowned/orphaned.
My downloads use categories and each category has a distinct save path. E.g. `/downloads/TV` and `/downloads/Movies`.
I think what's happening is that absolute paths from qbittorrent are constructed like `/downloads` + `file name` and thus never match the real files.
Maybe a better approach would be mapping the real save paths inside the container. You could traverse all the save paths you get from qbittorrent without having to translate paths.

Writing this, I think a possible workaround for me could be running one instance per category, using "ignore labels" to leave the other categories alone.

**Comment by dGstone18** [comment]
Would love to see this be supported. Was really excited to find this script but without multiple save path (category) support it is effectively useless for me.

**Comment by JakeWharton** [comment]
Working on this!

**Comment by dGstone18** [comment]
@JakeWharton I've updated to the latest version and it continues to mark every file as unowned and every torrent as unlinked. I have all of my torrents categorized. I believe the issue should be reopened. Is there any more info I can provide to assist?

**Comment by JakeWharton** [comment]
I tested it by mounting `/downloads` in the container to `/test` locally, and having `/test/complete` and `/test/hello` download folders in the client based on category. Then I put a few torrents in each category and thus each folder.

You can get some logs by running the container with `DEBUG=true`.

The only other thing to check would be to ensure you are using hardlinks, and that commands like `ls -l` show the hard link count of files in the download folders to be >1. E.g.,
```
﻿﻿﻿jake@theswan /t/m/D/c/Star Wars Despecialized 2.7 MKV> ls -l
total 20946124
-rw-r--r-- 2 jake jake 21454398564 Aug 19  2022  Star.Wars.Despecialized.Edition.v2.7.mkv
drwxr-xr-x 7 jake jake          10 Aug 19  2022 'Subtitles Project Threepio v9.2'/
-rw-r--r-- 1 jake jake        8767 Aug 19  2022 'SW 2.7 Readme.txt'
```
(Note the 2 next to the actual movie file)

I can re-open, but I can't really do anything without some kind of reproduction steps.

**Comment by D4rkm3ch** [comment]
Can confirm this still doesn't work. My torrents are automatically managed by my Arrs which in turn create their own download directories: radarr, tv-sonarr, lidarr. Therefore, my downloads have multiple sub directories which then all get tagged as Unlinked. I have tried every way to mount the volume download path for this container to no success.

qbit downloads: `/mnt/Swimming/plexmedia/downloads/torrents`
qbit download subdirectories eg1: `/mnt/Swimming/plexmedia/downloads/torrents/radarr`

I've tried mounting the volume to the container as such:
`/mnt/Swimming/plexmedia/`
`/mnt/Swimming/plexmedia/downloads/torrents/`
`/mnt/Swimming/plexmedia/downloads/torrents/radarr`

Always says everything is unlinked. Can confirm hardlinks are working and are being placed in: `/mnt/Swimming/plexmedia/media`

Here is my TrueNAS hardlink proof using shell and ls -al:

`-rwxrwxr-x  2 d4rkm3ch d4rkm3ch-users 19375014079 Dec 13 14:27 'Cinderella (1950) - 35mm.mkv'`
`-rwxrwxr-x  2 d4rkm3ch d4rkm3ch-users 20912534021 Dec 13 14:27 'Mulan (1998) - 35mm.mkv'`

**Comment by JakeWharton** [comment]
What path is mounted to your torrent client?

**Comment by D4rkm3ch** [comment]
`/mnt/Swimming/plexmedia/downloads/torrents:/plexmedia/downloads/torrents`

Below is my complete compose. I only just now hashed out the orphan code since it's currently not working.

```
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080 # qbit
      - 6881:6881 # qbit
      - 6881:6881/udp # qbit
    volumes:
      - /mnt/Swimming/Sandboxes/docker/gluetun/config/config.toml:/gluetun/auth/config.toml:ro
    environment:
      - TZ=Australia/Sydney
      - PUBLICIP_API=ipinfo
      - PUBLICIP_API_TOKEN=
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - VPN_PORT_FORWARDING=on
      - OPENVPN_USER=+pmp
      - OPENVPN_PASSWORD=
      - UPDATER_PERIOD=24h
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    labels:
      com.centurylinklabs.watchtower.enable: false
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Australia/Sydney
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - DOCKER_MODS=ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main
      - GSP_GTN_API_KEY=
      - GSP_MINIMAL_LOGS=false
      - GSP_RETRY_DELAY=10
    volumes:
      - /mnt/Swimming/Sandboxes/docker/qbittorrent/config:/config
      - /mnt/Swimming/plexmedia/downloads/torrents:/plexmedia/downloads/torrents
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: service:gluetun
#  qbt-orphaned-downloads:
#    container_name: qbt-orphaned-downloads
#    image: jakewharton/qbt-orphaned-downloads:latest
#    restart: unless-stopped
#   volumes:
#     - /mnt/Swimming/plexmedia:/plexmedia
#   environment:
#     - QBT_HOST=http://192.168.4.59:8080
#     - CRON=* * * * *
#     - QBT_USER=
#     - QBT_PASS=
networks: {}
```
